---
- hosts: example
  tasks:
    - name: holy_work
      apt: update_cache=yes

    - name: sacred_work
      apt: pkg=* state=latest   

    - name: install_docker.io
      apt: pkg=docker.io state=latest 

    - name: file_absent_git
      file: dest=/root/example state=absent
      ignore_errors: yes

    - name: git_clone_my_repositiory
      shell: git clone https://github.com/Skepchest/example.git
      ignore_errors: yes
    
    - name: copy_script_to_/bin/sh
      copy: src=ansible/docker dest=/bin/sh  
    
    - name: run_script_docker
      shell: ./docker
